language: 
    - python
python:
    - "2.7"
    - "3.6"
# command to install dependencies
install: 
    - sudo apt-get update
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda config --add channels r
    - conda config --add channels bioconda


    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
        cython numpy networkx seaborn pyBigwig six pysam ujson pytest scipy 
        matplotlib samtools future
    - source activate test-environment
    - pip install .
    - for SAM in test/data/*sam; do samtools view -b $SAM > ${SAM%.sam}.bam; echo made ${SAM%.sam}.bam; done
    - samtools sort -o test/data/MT_TF.sorted.bam /test/data/MT_TF.bam
    - samtools index test/data/MT_TF.sorted.bam
    - samtools faidx test/data/MT_TF.fa
# # command to run tests
script: 
    - pytest
    - bash test_script.sh
