# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        $CONDA/bin/conda config --set always_yes yes --set changeps1 no
        $CONDA/bin/conda update -q conda
        # Useful for debugging any issues with conda
        $CONDA/bin/conda info -a
        $CONDA/bin/conda config --add channels bioconda
        $CONDA/bin/conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION cython numpy networkx seaborn pyBigwig six pysam ujson pytest scipy matplotlib samtools future pytest-cov codecov
        $CONDA/bin/conda activate test-environment
        pip install .

        
    - name: make tes files
      run: |
        $CONDA/bin/conda activate test-environment
        for SAM in test/data/*sam; do samtools view -b $SAM > ${SAM%.sam}.bam; echo made ${SAM%.sam}.bam; done
        samtools index test/data/MT_TF.bam
        samtools faidx test/data/MT_TF.fa
    - name: Test with pytest
      run: |
        $CONDA/bin/conda
        pytest --cov=./
        bash test_script.sh
    - name: codecov
      run: |
        codecov
