# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-environment
          python-version: 3.6
          channels: bioconda anaconda default
          allow-softlinks: true
          channel-priority: bioconda
          show-channel-urls: true
          use-only-tar-bz2: true
          auto-update-conda: true
      runs: |
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a


    - name: Install dependencies
      run: |
        conda install  python=$TRAVIS_PYTHON_VERSION cython numpy networkx seaborn pyBigwig six pysam ujson pytest scipy matplotlib samtools future pytest-cov codecov
        pip install .

    - name: make test files
      run: |
        for SAM in test/data/*sam; do samtools view -b $SAM > ${SAM%.sam}.bam; echo made ${SAM%.sam}.bam; done
        samtools index test/data/MT_TF.bam
        samtools faidx test/data/MT_TF.fa

    - name: Test with pytest
      run: |
        pytest --cov=./
        bash test_script.sh

    - name: codecov
      run: |
        codecov
