# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: miniconda CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 20
    name: miniconda build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-environment
          python-version: 3.6
          channels: bioconda,default,anaconda
          allow-softlinks: true
          channel-priority: 'flexible'
          show-channel-urls: true
          use-only-tar-bz2: true
          auto-update-conda: true

      - name: setup conda
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda info -a
          conda list
          conda config --show-sources
          conda config --show


      - name: Install dependencies
        run: |
          conda install -c bioconda -c conda-forge \
                python=3.6 cython \
                numpy=1.18.4 networkx=2.4 seaborn pandas=1.0.4 \
                pyBigwig=0.3.17 six pysam=0.16.0.1 ujson pytest \
                scipy=1.4.1 matplotlib \
                samtools=1.9 future pytest-cov codecov

      - name: Install sequencing_tools
        run: |
          python setup.py install

      - name: make test files
        run: |
          for SAM in test/data/*sam; do samtools view -b $SAM > ${SAM%.sam}.bam; echo made ${SAM%.sam}.bam; done 
          samtools index test/data/MT_TF.bam 
          samtools faidx test/data/MT_TF.fa 

      - name: Test with pytest
        run: |
          pytest --cov=./  -l  -rPap -vvv -p no:warnings
          bash test_script.sh

      - name: codecov
        run: |
          codecov

